require:
  - rubocop-rspec

AllCops:
  TargetRubyVersion: 2.6
  NewCops: enable

# rubocop

Metrics/BlockLength:
  Exclude:
    - spec/**/*

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

# rubocop-rspec

RSpec/ExampleLength:
  Enabled: false
