#!/usr/bin/env ruby

require 'optparse'
require 'fuji_markdown'

option = :HTML

OptionParser.new do |opts|
  opts.banner = 'Usage: fujimd [--output <format>] <file>...'

  opts.on('-o', '--output FORMAT', 'Specify output format: kakuyomu, narou or html') do |fmt|
    option = fmt.upcase.to_sym
  end

  opts.on_tail('-v', '--version', 'Display the current version') do
    puts FujiMarkdown::VERSION
    exit
  end

  opts.on_tail('-h', '--help', 'Display this help message') do
    puts opts
    exit
  end
end.parse!

puts FujiMarkdown.render(ARGF.read, option)
